# Generated by Django 4.2.5 on 2023-09-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=256)),
                ('foodType', models.CharField(max_length=256)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
